CREATE DATABASE Software_VirtualVerseStudios;
USE Software_VirtualVerseStudios;

CREATE TABLE Games(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(45) NOT NULL,
Plataformas_id INT NOT NULL,
Catalogo_id INT NOT NULL,
FOREIGN KEY (Plataformas_id) REFERENCES Plataformas(ID),
FOREIGN KEY (Catalogo_id) REFERENCES Catalogo(ID)
);

CREATE TABLE Catalogo(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Loja_id INT NULL,
FOREIGN KEY (Loja_id) REFERENCES Loja(ID)
);

CREATE TABLE Plataformas(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(45) NOT NULL,
Fabricante VARCHAR(45) NOT NULL,
Tipo VARCHAR(50) NOT NULL,
Loja_id INT NULL,
FOREIGN KEY (Loja_id) REFERENCES Loja(ID)
);

CREATE TABLE Conteudo(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Tipo_Conteudo VARCHAR(45) NOT NULL,
Loja_id INT NULL,
FOREIGN KEY (Loja_id) REFERENCES Loja(ID)
);

CREATE TABLE Conteudo_Games(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Conteudo_id INT NOT NULL,
Games_id INT NOT NULL,
FOREIGN KEY (Conteudo_id) REFERENCES Conteudo(ID),
FOREIGN KEY (Games_id) REFERENCES Games(ID)
);

CREATE TABLE CategoriaGeneros(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(45) NOT NULL,
Loja_id INT NULL,
FOREIGN KEY (Loja_id) REFERENCES Loja(ID)
);

CREATE TABLE Games_CategoriaGeneros(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Games_id INT NOT NULL,
CategoriaGeneros_id INT NOT NULL,
FOREIGN KEY (Games_id) REFERENCES Games(ID),
FOREIGN KEY (CategoriaGeneros_id) REFERENCES CategoriaGeneros(ID)
);

CREATE TABLE Loja(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Busca VARCHAR(255) NOT NULL
);

CREATE TABLE Carrinho_de_Compras(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Loja_id INT NULL,
Data_Ultima_Atualizacao DATETIME NOT NULL,
Status ENUM("Ativo", "Finalizado", "Abandonado", "Cancelado"),
Total DECIMAL(9,2) NOT NULL,
FOREIGN KEY (Loja_id) REFERENCES Loja(ID)
);

CREATE TABLE Usuarios(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(45) NOT NULL,
Data_nascimento DATE NOT NULL,
Pais_Regiao VARCHAR(45) NOT NULL,
Idioma VARCHAR(45) NOT NULL,
Endereco VARCHAR(255) NOT NULL,
ID_Online VARCHAR(45) NOT NULL,
Email VARCHAR(45) NOT NULL,
Senha VARCHAR(45) NOT NULL,
Loja_id INT NULL,
Forum_id INT NOT NULL,
PlanoPremium_id INT NULL,
FOREIGN KEY (Loja_id) REFERENCES Loja(ID),
FOREIGN KEY (Forum_id) REFERENCES Forum(ID),
FOREIGN KEY (PlanoPremium_id) REFERENCES Plano_Premium(ID)
);

CREATE TABLE Plano_Premium(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Ofertas_id INT NOT NULL,
Recompensas_id INT NOT NULL,
Loja_id INT NULL,
FOREIGN KEY (Ofertas_id) REFERENCES Ofertas(ID),
FOREIGN KEY (Recompensas_id) REFERENCES Recompensas(ID),
FOREIGN KEY (Loja_id) REFERENCES Loja(ID)
);

CREATE TABLE Ofertas(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Tipo_Oferta VARCHAR(100) NOT NULL,
Valor_Desconto DECIMAL(5,2) NOT NULL,
Percentual_Desconto DECIMAL(5,2) NOT NULL,
Jogo_Aplicavel VARCHAR(255) NOT NULL,
Descricao TEXT(1000) NOT NULL,
Games_id INT NULL,
FOREIGN KEY (Games_id) REFERENCES Games(ID)
);

CREATE TABLE Recompensas(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Tipo_Recompensa VARCHAR(100) NOT NULL,
Descricao TEXT(1000) NOT NULL,
Games_id INT NULL,
FOREIGN KEY (Games_id) REFERENCES Games(ID)
);

CREATE TABLE Forum(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Topicos VARCHAR(255) NOT NULL,
Categorias VARCHAR(255) NOT NULL,
Postagens VARCHAR(255) NOT NULL,
Respostas VARCHAR(255) NOT NULL,
Moderacao VARCHAR(255) NOT NULL,
Mensagens VARCHAR(255) NOT NULL,
Citacoes VARCHAR(255) NOT NULL,
Reacoes VARCHAR(255) NOT NULL,
Notificacoes VARCHAR(255) NOT NULL,
Busca VARCHAR(255) NOT NULL,
Multimidia VARCHAR(255) NOT NULL,
Formatacao_de_texto VARCHAR(45) NOT NULL,
Configuracoes VARCHAR(255) NOT NULL
);

CREATE TABLE Noticias(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Titulo VARCHAR(255) NOT NULL,
Subtitulo VARCHAR(255) NOT NULL,
Resumo VARCHAR(200) NOT NULL,
Conteudo TEXT(1000) NOT NULL,
Autor VARCHAR(45) NOT NULL,
Data_publicacao DATETIME NOT NULL,
Data_atualizacao DATETIME NOT NULL,
Imagem_principal VARCHAR(255) NOT NULL,
Slug VARCHAR(45) NOT NULL,
Status ENUM('Rascunho', 'Em Revisão', 'Aprovado', 'Publicado', 'Arquivado', 'Deletado') NOT NULL,
Visualizacoes INT NOT NULL,
Palavras_chave VARCHAR(255) NOT NULL,
Importante BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE Imagens(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Noticias_id INT NOT NULL,
Caminho_Imagem VARCHAR(255) NOT NULL,
Legenda VARCHAR(255) NOT NULL,
FOREIGN KEY (Noticias_id) REFERENCES Noticias(ID)
);

CREATE TABLE Videos(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Forum_id INT NOT NULL,
URL_Video VARCHAR(255) NOT NULL,
Titulo VARCHAR(255) NOT NULL,
Legenda VARCHAR(255) NOT NULL,
FOREIGN KEY (Forum_id) REFERENCES Forum(ID)
);

CREATE TABLE Noticias_Videos(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Noticias_id INT NOT NULL,
Videos_id INT NOT NULL,
FOREIGN KEY (Noticias_id) REFERENCES Noticias(ID),
FOREIGN KEY (Videos_id) REFERENCES Videos(ID)
);

CREATE TABLE Suporte(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Forum_id INT NULL,
FAQs VARCHAR(255) NOT NULL,
Tutoriais VARCHAR(255) NOT NULL,
Pesquisa VARCHAR(255) NOT NULL,
FOREIGN KEY (Forum_id) REFERENCES Forum(ID)
);

CREATE TABLE Categorias_Suporte(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Conta VARCHAR(45) NOT NULL,
Seguranca VARCHAR(45) NOT NULL,
Compras VARCHAR(45) NOT NULL,
Reembolsos VARCHAR(45) NOT NULL,
Assinaturas VARCHAR(45) NOT NULL,
Jogos VARCHAR(45) NOT NULL,
Jogabilidade VARCHAR(45) NOT NULL,
Detonados VARCHAR(45) NOT NULL,
Conectividade VARCHAR(45) NOT NULL,
Suporte_id INT NULL,
FOREIGN KEY (Suporte_id) REFERENCES Suporte(ID)
);
